version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    target-branch: main
    labels:
      - bot
      - dependencies
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:00"
      timezone: Europe/Paris
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-name: "*"
        dependency-type: direct
    ignore:
      - dependency-name: "@types/*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
      - dependency-name: "@types/node"
        versions:
          - ">=18"
