version: "3.8"

services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapi
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

  strapi:
    image: mda-strapi
    build:
      context: .
      dockerfile: apps/strapi/Dockerfile
    environment:
      DATABASE_HOST: db
      HOST: 0.0.0.0
    env_file:
      - apps/strapi/.env
    ports:
      - 1337:1337

  web:
    image: mda-web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_STRAPI_API_URL: http://strapi:1337
        PRODUCTION: "false"
    environment:
      PRODUCTION: "false"
    env_file:
      - apps/web/.env.development.local
    ports:
      - 3000:3000

  maildev:
    image: djfarrelly/maildev
    command: bin/maildev --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_SMTP_PORT}:${MAILDEV_SMTP_PORT}"
      - "${MAILDEV_WEB_PORT}:${MAILDEV_WEB_PORT}"
    environment:
      MAILDEV_WEB_PORT: ${MAILDEV_WEB_PORT}
      MAILDEV_SMTP_PORT: ${MAILDEV_SMTP_PORT}
    restart: always

volumes:
  pgdata:
