strapi:
  ~needs: [build-strapi, strapi-import-content]

jobs:
  runs:
    build-web:
      with:
        buildArgs:
          PRODUCTION: "true"
          NEXT_PUBLIC_STRAPI_API_URL: "https://strapi-{{ .Values.global.host }}"
    create-db:
      use: create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
    build-strapi:
      ~needs: [create-db]
    strapi-import-content:
      ~needs: [build-strapi]
      retry: 0
      checkout: false
      image: "{{ .Values.global.registry }}/{{ .Values.global.imageProject }}/{{ .Values.global.imageRepository }}/strapi:{{ .Values.global.imageTag }}"
      envFrom:
        - secretRef:
            name: "{{ .Values.global.pgSecretName }}"
        - secretRef:
            name: "mda-strapi"
      vars:
        DATABASE_HOST: "$(PGHOST)"
        DATABASE_PORT: "$(PGPORT)"
        DATABASE_NAME: "$(PGDATABASE)"
        DATABASE_USERNAME: "$(PGUSER)"
        DATABASE_PASSWORD: "$(PGPASSWORD)"
        DATABASE_SSL: "$(PGSSLMODE)" # invetigate why knex doesn't work with "ssl: require"
        HOST: "0.0.0.0"
        MDA_ENV: "{{ .Values.global.env }}"
      run: |
        strapi import --only content --force --file content-dump.tar.gz
