apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: mda-revalidate-webhook
  namespace: null
spec:
  encryptedData:
    WEBHOOK_REVALIDATE_TOKEN: AgDMs68WWOSD+WfuHqpfTsW9AaxNAwd8bOrApNMz+xArLuFTDSfLtLjPwXOv1tNohJtmHdK/bmCZ80KE4vGQQYH4m5ihQFBJ055p7h6zGnGbNz9gNqz7YJwLg2s3I01rFHn8QLwNmfgo/KpCpK/tKdMck9M2wE6WmqxixNG+o3rKT4fMw97RuAS8XzaoR2YTQhMkpU3ks6EloFnlBB2Z4geiAcPcqVyp8ssSC2P21J0oKhCnJHoLVOZA+Kg634YyPNSE14XEeEzXuFQvrtFXc1vO9sKjG+9o8bS0x9NbcRek2lWL9MbTn1AKelZcdVI4Om3gqc2JcxZn1xXwMcNLnhTG+c1qRDOXwHJQ3jwbSPxeO7zHJl2ZDtgeI9Uj0ANBPfyY53cdPj29exdjPcI9cBWOJ1gNoqVACmcDzSNv9BbvnhWw/2OBzmnkuWg4FG5x4Utc/+ElSy+k96BXUhROj7P9dOPOfwxcU94ytQYcbUTInsEG/9KNMk8Ys5eTd+mEoaQ8kf9heOW+TAFKkd3nyF7v+LL4x83M5VGf41RiVBCHjtoudXwb1a4pGcS6arfjfvIVvfr/aoFLJhBh+nrpQ+/Y+z4Cz3nxPGFemQbDjDEzc7j+ZNqtVFReZpYqi2ByiKw2BQpYvG77yXvxnZwDpMyLH0VxEcrqgeTeSOT1Zhpu/eK0GJ6jbdXDRRHiHzDnfFSx85SvQx8E1qfW3J1mKQO6l8Pl1bmahsgLtDH/wuY8sT5HriacIl8HV2l/dw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: mda-revalidate-webhook
    type: Opaque