apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: mda-meilisearch
spec:
  encryptedData:
    MEILISEARCH_MASTER_KEY: AgCmXuIGm1JUv6Nu7aORCZSQZFI4M8YE6+K0HjOF8rBCEjxLj5D5gN0/bdDzMQAB6qkyrfvFJA2kElUzaaedvEoiTA9dzPevPKeiQLHo1DpXZhhyuihY4WrRCvHhFGSgWBm/zxYphhxMAWvf2+vhflJ/C8qdI5mocqhDFjiMqD0TIRRKk4Tk5C4NftS35liHlSbUSRQPsrPDhOQ4+BpPI7tvK2H1PTK5SkznUFGyNDf7AMAE5SFpKTkdIv0j4H3GEey1O8bpkA86VlF0tr1EwZFzwEWMpnNHGNgGDyL2y/KMlaDAvKWFT47B8NTqzvpfGZyggshT/Y/HZO1/iyJ4jfuKddXMA25qlGgZW7+bKKtXPLDEV7MijUlxOWSPu/s9tv14jVKEqCuS0HUlRNt/HF2w+BvFByEsAAt6F9uOzt2VUIHY5Z+7ZHR4XlfgX25bThGdXa0GF/m9pJUruhgpwSpkfPbD3BLkubrBChLZhoQEfYiTm9/ajDmnMyjX07+/lfLE5KQo0qScKYez3O4n1GukoCWMLgH0J1rrQF9au+TS9fzvMN3jRh9RIgMIq2pTpIALHqfYYtsthZWipXnK8adx5SNvco3JgJojvOAzXFlkSCtNVPaWhZABvv9/KdTKi5EYkwqBtxsReKmm1SB9gPZ1xoFFn7zzFVyJkBN93j1HVblKiX4T7aMXBLNjMj4yKWPCzDsPonKrQWWI+87tmV4SCwJFkIBk4WOf9+2Hutjn5MhHTsx6fz63v1cIhw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: mda-meilisearch
    type: Opaque
