projectName: maison-de-l-autisme
repositoryName: mda

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique

app:
  vars:
    MAILER_ENABLE: "True"
    MAILER_SMTP_HOST: maildev
    MAILER_SMTP_PORT: "1025"
    MAILER_SMTP_LOGIN: ""
    MAILER_SMTP_PASSWORD: ""
    MAILER_SMTP_SSL: "False"