projectName: maison-de-l-autisme
repositoryName: mda

dependencies:
  fabrique:
    extends:
      - name: buildkit-service
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                maison-de-l-autisme-dev-backups-access-key:
                maison-de-l-autisme-prod-backups-access-key: