global:
  registry: harbor.fabrique.social.gouv.fr
  imageProject: maison-de-l-autisme
  imageRepository: mda

web:
  ~chart: app
  containerPort: 3000
  ~needs: [build-web]
  imagePackage: web
  probesPath: /healthz
  host: "{{ .Values.global.host }}"
  envFrom:
    - secretRef:
        name: "mda-revalidate-webhook"
  vars:
    NEXT_PUBLIC_SITE_URL: "{{ .Values.global.host }}"
    MDA_ENV: "{{ .Values.global.env }}"

strapi:
  ~chart: app
  containerPort: 1337
  ~needs: [build-strapi]
  imagePackage: strapi
  probesPath: /_health
  host: "strapi-{{ .Values.global.host }}"
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: "mda-strapi"
    - secretRef:
        name: "mda-revalidate-webhook"
  vars:
    DATABASE_HOST: "$(PGHOST)"
    DATABASE_PORT: "$(PGPORT)"
    DATABASE_NAME: "$(PGDATABASE)"
    DATABASE_USERNAME: "$(PGUSER)"
    DATABASE_PASSWORD: "$(PGPASSWORD)"
    DATABASE_SSL: "$(PGSSLMODE)" # invetigate why knex doesn't work with "ssl: require"
    HOST: "0.0.0.0"
    GITHUB_SHA: "{{ $.Values.global.sha }}"
    MDA_ENV: "{{ .Values.global.env }}"
    WEB_URL: "{{ .Values.global.host }}"

jobs:
  runs:
    build-web:
      ~needs: [strapi]
      use: build
      with:
        imagePackage: web
        dockerfile: apps/web/Dockerfile
        buildArgs:
          NEXT_PUBLIC_GITHUB_SHA: "{{ $.Values.global.sha }}"
          NEXT_PUBLIC_SITE_URL: "{{ .Values.global.host }}"
          NEXT_PUBLIC_STRAPI_API_URL: "https://strapi-{{ .Values.global.host }}"
          MDA_ENV: "{{ .Values.global.env }}"

    build-strapi:
      use: build
      with:
        imagePackage: strapi
        dockerfile: apps/strapi/Dockerfile

deactivate:
  jobs-deactivate:
    runs:
      deactivate:
        with:
          db: true