global:
  registry: harbor.fabrique.social.gouv.fr
  imageProject: maison-de-l-autisme
  imageRepository: mda

meilisearch:
  ~chart: app
  image: getmeili/meilisearch:v1.1.0
  containerPort: 7700
  probesPath: /health
  envFrom:
    - secretRef:
        name: "mda-meilisearch"
  env:
    - name: MEILI_NO_ANALYTICS
      value: "true"
    - name: MEILI_DB_PATH
      value: /meilifiles
  ingress:
    enabled: false

web:
  ~chart: app
  containerPort: 3000
  ~needs:
    - build-web
  imagePackage: web
  probesPath: /healthz
  host: "{{ .Values.global.host }}"
  envFrom:
    - secretRef:
        name: "mda-revalidate-webhook"
  vars:
    NEXT_PUBLIC_SITE_URL: "https://{{ .Values.global.host }}"
    MDA_ENV: "{{ .Values.global.env }}"

pg:
  ~chart: pg

strapi:
  ~chart: app
  containerPort: 1337
  ~needs:
    - build-strapi
    - meilisearch
  imagePackage: strapi
  probesPath: /_health
  host: "strapi.{{ .Values.global.host }}"
  envFrom:
    - secretRef:
        name: "pg-app"
    - secretRef:
        name: "mda-strapi"
    - secretRef:
        name: "mda-revalidate-webhook"
    - secretRef:
        name: "mda-matomo"
    - secretRef:
        name: "mda-meilisearch"
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 512m
  vars:
    DATABASE_HOST: "$(PGHOST)"
    DATABASE_PORT: "$(PGPORT)"
    DATABASE_NAME: "$(PGDATABASE)"
    DATABASE_USERNAME: "$(PGUSER)"
    DATABASE_PASSWORD: "$(PGPASSWORD)"
    DATABASE_SSL: "$(PGSSLMODE)" # invetigate why knex doesn't work with "ssl: require"
    HOST: "0.0.0.0"
    GITHUB_SHA: "{{ $.Values.global.shortSha }}"
    MATOMO_SITE_ID: "81"
    MATOMO_URL: "https://matomo.fabrique.social.gouv.fr"
    MDA_ENV: "{{ .Values.global.env }}"
    WEB_URL: "https://{{ .Values.global.host }}"
    MEILISEARCH_HOST: "http://meilisearch"

jobs:
  runs:
    build-web:
      ~needs:
        - strapi
      use: build
      with:
        imagePackage: web
        dockerfile: apps/web/Dockerfile
        buildArgs:
          NEXT_PUBLIC_GITHUB_SHA: "{{ $.Values.global.shortSha }}"
          NEXT_PUBLIC_SITE_URL: "https://{{ .Values.global.host }}"
          NEXT_PUBLIC_STRAPI_API_URL: "https://strapi.{{ .Values.global.host }}"
          MDA_ENV: "{{ .Values.global.env }}"

    build-strapi:
      use: build
      ~needs: [pg]
      with:
        imagePackage: strapi
        dockerfile: apps/strapi/Dockerfile

deactivate:
  jobs-deactivate:
    runs:
      deactivate:
        with:
          db: true
