name: ♻️ Deactivate
on:
  pull_request:
    types: [closed]
  delete:
    branches:
      - "**"
      - "!v*"
      - "!main"

jobs:
  kontinuous:
    uses: socialgouv/workflows/.github/workflows/use-ks-wh-deactivate.yaml@v1
    secrets: inherit